import {
  UserProfile,
  Client,
  Campaign,
  Area,
  Booth,
  Volunteer,
  Voter,
  Task,
  FieldActivity,
  FollowUp,
  Subscription,
  AuditLog,
} from "../types";

export const INITIAL_PROFILES: UserProfile[] = [
  {
    id: "user-super-admin",
    email: "superadmin@chunavsetu.com",
    full_name: "Vikramaditya Rao",
    role: "super_admin",
    mobile: "+91 98111 00001",
    status: "active",
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "user-client-1",
    email: "rajesh.sharma@chunavsetu.com",
    full_name: "Rajesh Sharma",
    role: "client_admin",
    client_id: "client-1",
    mobile: "+91 98201 12345",
    status: "active",
    created_at: "2026-01-10T00:00:00Z",
  },
  {
    id: "user-client-2",
    email: "priya.verma@chunavsetu.com",
    full_name: "Priya Verma",
    role: "client_admin",
    client_id: "client-2",
    mobile: "+91 98450 54321",
    status: "active",
    created_at: "2026-02-01T00:00:00Z",
  },
  {
    id: "user-client-3",
    email: "anil.deshmukh@chunavsetu.com",
    full_name: "Anil Deshmukh",
    role: "client_admin",
    client_id: "client-3",
    mobile: "+91 97110 98765",
    status: "active",
    created_at: "2026-02-15T00:00:00Z",
  },
  {
    id: "user-volunteer-1",
    email: "amit.volunteer@chunavsetu.com",
    full_name: "Amit Kumar",
    role: "volunteer",
    client_id: "client-1",
    mobile: "+91 99190 11223",
    status: "active",
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "user-volunteer-2",
    email: "sunita.v@chunavsetu.com",
    full_name: "Sunita Tripathi",
    role: "volunteer",
    client_id: "client-1",
    mobile: "+91 94150 33445",
    status: "active",
    created_at: "2026-03-05T00:00:00Z",
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: "client-1",
    name: "Sharma Campaign HQ",
    candidate_name: "Rajesh Sharma",
    mobile: "+91 98201 12345",
    email: "rajesh.sharma@chunavsetu.com",
    campaign_name: "Central Assembly 2026",
    election_type: "Vidhan Sabha",
    location: "Lucknow Central (AC-174)",
    status: "active",
    created_at: "2026-01-10T10:00:00Z",
    voter_count: 1450,
    volunteer_count: 8,
    booth_count: 4,
    campaign_count: 1,
  },
  {
    id: "client-2",
    name: "Verma Vikas Samiti",
    candidate_name: "Priya Verma",
    mobile: "+91 98450 54321",
    email: "priya.verma@chunavsetu.com",
    campaign_name: "North Ward Municipal 2026",
    election_type: "Municipal Corporation",
    location: "Varanasi North Ward 14",
    status: "active",
    created_at: "2026-02-01T11:30:00Z",
    voter_count: 820,
    volunteer_count: 4,
    booth_count: 2,
    campaign_count: 1,
  },
  {
    id: "client-3",
    name: "Deshmukh Janshakti Office",
    candidate_name: "Anil Deshmukh",
    mobile: "+91 97110 98765",
    email: "anil.deshmukh@chunavsetu.com",
    campaign_name: "South Parliamentary 2026",
    election_type: "Lok Sabha",
    location: "Pune South Constituency",
    status: "active",
    created_at: "2026-02-15T09:15:00Z",
    voter_count: 2600,
    volunteer_count: 15,
    booth_count: 8,
    campaign_count: 1,
  },
];

export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: "camp-1",
    client_id: "client-1",
    title: "Lucknow Central Assembly Campaign 2026",
    description: "Focus on youth employment, municipal infrastructure, and clean piped water connectivity.",
    election_date: "2026-11-15",
    target_voters: 125000,
    status: "active",
    created_at: "2026-01-10T10:00:00Z",
  },
  {
    id: "camp-2",
    client_id: "client-2",
    title: "Varanasi Ward 14 Sanitation & Development",
    description: "Ward level door-to-door resident engagement and rapid civic grievance redressal.",
    election_date: "2026-10-20",
    target_voters: 18000,
    status: "active",
    created_at: "2026-02-01T11:30:00Z",
  },
  {
    id: "camp-3",
    client_id: "client-3",
    title: "Pune South Vision 2026",
    description: "Constituency-wide outreach across all 6 assembly segments with booth committee mobilization.",
    election_date: "2026-12-05",
    target_voters: 450000,
    status: "active",
    created_at: "2026-02-15T09:15:00Z",
  },
];

export const INITIAL_AREAS: Area[] = [
  // Client 1 Areas
  {
    id: "area-1",
    client_id: "client-1",
    campaign_id: "camp-1",
    name: "Hazratganj Main",
    ward_number: "Ward 08",
    pincode: "226001",
    description: "High commercial & residential blend near MG Marg.",
    created_at: "2026-01-11T09:00:00Z",
    booth_count: 2,
  },
  {
    id: "area-2",
    client_id: "client-1",
    campaign_id: "camp-1",
    name: "Alambagh Market",
    ward_number: "Ward 12",
    pincode: "226005",
    description: "Dense residential trading community.",
    created_at: "2026-01-11T09:30:00Z",
    booth_count: 1,
  },
  {
    id: "area-3",
    client_id: "client-1",
    campaign_id: "camp-1",
    name: "Mahanagar Sector B",
    ward_number: "Ward 22",
    pincode: "226006",
    description: "Middle-income residential colony.",
    created_at: "2026-01-11T10:00:00Z",
    booth_count: 1,
  },

  // Client 2 Areas
  {
    id: "area-4",
    client_id: "client-2",
    campaign_id: "camp-2",
    name: "Cantonment North",
    ward_number: "Ward 14A",
    pincode: "221002",
    description: "Northern ward boundary blocks.",
    created_at: "2026-02-02T10:00:00Z",
    booth_count: 1,
  },
  {
    id: "area-5",
    client_id: "client-2",
    campaign_id: "camp-2",
    name: "Shivpur Colony",
    ward_number: "Ward 14B",
    pincode: "221003",
    description: "Inner residential mohalla.",
    created_at: "2026-02-02T10:30:00Z",
    booth_count: 1,
  },

  // Client 3 Areas
  {
    id: "area-6",
    client_id: "client-3",
    campaign_id: "camp-3",
    name: "Kothrud Central",
    ward_number: "Segment 04",
    pincode: "411038",
    description: "Educational and IT residential zone.",
    created_at: "2026-02-16T11:00:00Z",
    booth_count: 4,
  },
];

export const INITIAL_BOOTHS: Booth[] = [
  // Client 1 Booths
  {
    id: "booth-101",
    client_id: "client-1",
    campaign_id: "camp-1",
    area_id: "area-1",
    area_name: "Hazratganj Main",
    booth_number: "Booth 101",
    booth_name: "Govt Inter College, Room 1",
    location_address: "Near Capitol Cinema, Hazratganj, Lucknow",
    target_voter_count: 1150,
    voter_count: 18,
    contacted_count: 12,
    assigned_volunteers_count: 2,
    progress_percentage: 67,
    created_at: "2026-01-12T10:00:00Z",
  },
  {
    id: "booth-102",
    client_id: "client-1",
    campaign_id: "camp-1",
    area_id: "area-1",
    area_name: "Hazratganj Main",
    booth_number: "Booth 102",
    booth_name: "Govt Girls High School, Room 3",
    location_address: "MG Marg, Hazratganj, Lucknow",
    target_voter_count: 980,
    voter_count: 14,
    contacted_count: 8,
    assigned_volunteers_count: 1,
    progress_percentage: 57,
    created_at: "2026-01-12T10:30:00Z",
  },
  {
    id: "booth-103",
    client_id: "client-1",
    campaign_id: "camp-1",
    area_id: "area-2",
    area_name: "Alambagh Market",
    booth_number: "Booth 103",
    booth_name: "Alambagh Community Center, Hall A",
    location_address: "Chander Nagar, Alambagh, Lucknow",
    target_voter_count: 1240,
    voter_count: 16,
    contacted_count: 9,
    assigned_volunteers_count: 1,
    progress_percentage: 56,
    created_at: "2026-01-12T11:00:00Z",
  },
  {
    id: "booth-104",
    client_id: "client-1",
    campaign_id: "camp-1",
    area_id: "area-3",
    area_name: "Mahanagar Sector B",
    booth_number: "Booth 104",
    booth_name: "St. Xavier Primary Wing",
    location_address: "Sector B Main Road, Mahanagar, Lucknow",
    target_voter_count: 1020,
    voter_count: 12,
    contacted_count: 4,
    assigned_volunteers_count: 1,
    progress_percentage: 33,
    created_at: "2026-01-12T11:30:00Z",
  },

  // Client 2 Booths
  {
    id: "booth-201",
    client_id: "client-2",
    campaign_id: "camp-2",
    area_id: "area-4",
    area_name: "Cantonment North",
    booth_number: "Booth 21",
    booth_name: "Prathmik Vidyalaya Cantt",
    location_address: "Old Cantt Road, Varanasi",
    target_voter_count: 850,
    voter_count: 10,
    contacted_count: 6,
    assigned_volunteers_count: 1,
    progress_percentage: 60,
    created_at: "2026-02-03T10:00:00Z",
  },
  {
    id: "booth-202",
    client_id: "client-2",
    campaign_id: "camp-2",
    area_id: "area-5",
    area_name: "Shivpur Colony",
    booth_number: "Booth 22",
    booth_name: "Shivpur Panchayat Bhavan",
    location_address: "Shivpur Market, Varanasi",
    target_voter_count: 910,
    voter_count: 8,
    contacted_count: 3,
    assigned_volunteers_count: 1,
    progress_percentage: 38,
    created_at: "2026-02-03T10:30:00Z",
  },
];

export const INITIAL_VOLUNTEERS: Volunteer[] = [
  // Client 1 Volunteers
  {
    id: "vol-1",
    client_id: "client-1",
    user_id: "user-volunteer-1",
    name: "Amit Kumar",
    mobile: "+91 99190 11223",
    email: "amit.volunteer@chunavsetu.com",
    assigned_booth_id: "booth-101",
    assigned_booth_name: "Booth 101 (Govt Inter College)",
    assigned_area_id: "area-1",
    assigned_area_name: "Hazratganj Main",
    status: "active",
    joining_date: "2026-03-01",
    notes: "Lead field worker for Hazratganj block.",
    created_at: "2026-03-01T10:00:00Z",
    total_contacts: 24,
    pending_tasks: 2,
    completed_tasks: 8,
  },
  {
    id: "vol-2",
    client_id: "client-1",
    user_id: "user-volunteer-2",
    name: "Sunita Tripathi",
    mobile: "+91 94150 33445",
    email: "sunita.v@chunavsetu.com",
    assigned_booth_id: "booth-102",
    assigned_booth_name: "Booth 102 (Govt Girls High School)",
    assigned_area_id: "area-1",
    assigned_area_name: "Hazratganj Main",
    status: "active",
    joining_date: "2026-03-05",
    notes: "Focusing on women voters outreach and SHG networks.",
    created_at: "2026-03-05T10:00:00Z",
    total_contacts: 19,
    pending_tasks: 1,
    completed_tasks: 6,
  },
  {
    id: "vol-3",
    client_id: "client-1",
    name: "Vikas Mishra",
    mobile: "+91 97920 55667",
    email: "vikas.m@chunavsetu.com",
    assigned_booth_id: "booth-103",
    assigned_booth_name: "Booth 103 (Alambagh Community Center)",
    assigned_area_id: "area-2",
    assigned_area_name: "Alambagh Market",
    status: "active",
    joining_date: "2026-03-10",
    notes: "Merchant and shopkeeper liaison in Alambagh market.",
    created_at: "2026-03-10T10:00:00Z",
    total_contacts: 15,
    pending_tasks: 3,
    completed_tasks: 4,
  },
  {
    id: "vol-4",
    client_id: "client-1",
    name: "Pooja Srivastava",
    mobile: "+91 98390 88990",
    email: "pooja.s@chunavsetu.com",
    assigned_booth_id: "booth-104",
    assigned_booth_name: "Booth 104 (St. Xavier Primary Wing)",
    assigned_area_id: "area-3",
    assigned_area_name: "Mahanagar Sector B",
    status: "active",
    joining_date: "2026-03-12",
    notes: "Youth volunteer coordinator for Sector B.",
    created_at: "2026-03-12T10:00:00Z",
    total_contacts: 10,
    pending_tasks: 1,
    completed_tasks: 3,
  },

  // Client 2 Volunteers
  {
    id: "vol-201",
    client_id: "client-2",
    name: "Ramesh Pandey",
    mobile: "+91 94500 77889",
    email: "ramesh.p@chunavsetu.com",
    assigned_booth_id: "booth-201",
    assigned_booth_name: "Booth 21 (Prathmik Vidyalaya Cantt)",
    assigned_area_id: "area-4",
    assigned_area_name: "Cantonment North",
    status: "active",
    joining_date: "2026-02-10",
    notes: "Ward 14 lead surveyor.",
    created_at: "2026-02-10T10:00:00Z",
    total_contacts: 12,
    pending_tasks: 2,
    completed_tasks: 5,
  },
];

export const INITIAL_VOTERS: Voter[] = [
  // Client 1 - Booth 101 Voters
  {
    id: "voter-101-1",
    client_id: "client-1",
    campaign_id: "camp-1",
    booth_id: "booth-101",
    booth_number: "Booth 101",
    booth_name: "Govt Inter College, Room 1",
    area_id: "area-1",
    area_name: "Hazratganj Main",
    voter_id_card: "UP/48/281/001421",
    name: "Suresh Chandra Gupta",
    mobile: "+91 94150 12001",
    age: 54,
    gender: "Male",
    address: "H.No 12/A, Park Road, Hazratganj",
    contact_status: "favorable",
    follow_up_status: "none",
    notes: "Strong supporter. Wants discussion on trader tax simplification.",
    created_at: "2026-02-01T10:00:00Z",
    last_contacted_by: "Amit Kumar",
    last_contacted_at: "2026-03-15T11:20:00Z",
  },
  {
    id: "voter-101-2",
    client_id: "client-1",
    campaign_id: "camp-1",
    booth_id: "booth-101",
    booth_number: "Booth 101",
    booth_name: "Govt Inter College, Room 1",
    area_id: "area-1",
    area_name: "Hazratganj Main",
    voter_id_card: "UP/48/281/001422",
    name: "Meenakshi Gupta",
    mobile: "+91 94150 12002",
    age: 49,
    gender: "Female",
    address: "H.No 12/A, Park Road, Hazratganj",
    contact_status: "favorable",
    follow_up_status: "none",
    notes: "Appreciates women empowerment pledge in the manifesto.",
    created_at: "2026-02-01T10:00:00Z",
    last_contacted_by: "Amit Kumar",
    last_contacted_at: "2026-03-15T11:35:00Z",
  },
  {
    id: "voter-101-3",
    client_id: "client-1",
    campaign_id: "camp-1",
    booth_id: "booth-101",
    booth_number: "Booth 101",
    booth_name: "Govt Inter College, Room 1",
    area_id: "area-1",
    area_name: "Hazratganj Main",
    voter_id_card: "UP/48/281/001423",
    name: "Rohit Agarwal",
    mobile: "+91 98390 44551",
    age: 28,
    gender: "Male",
    address: "Flat 402, Royal Apartments, Hazratganj",
    contact_status: "undecided",
    follow_up_status: "pending",
    notes: "Concerned about parking congestion and commercial noise. Requested party manifesto copy.",
    created_at: "2026-02-01T10:00:00Z",
    last_contacted_by: "Amit Kumar",
    last_contacted_at: "2026-03-16T14:10:00Z",
  },
  {
    id: "voter-101-4",
    client_id: "client-1",
    campaign_id: "camp-1",
    booth_id: "booth-101",
    booth_number: "Booth 101",
    booth_name: "Govt Inter College, Room 1",
    area_id: "area-1",
    area_name: "Hazratganj Main",
    voter_id_card: "UP/48/281/001424",
    name: "Ananya Dixit",
    mobile: "+91 97920 66772",
    age: 23,
    gender: "Female",
    address: "H.No 45, Jopling Road, Hazratganj",
    contact_status: "contacted",
    follow_up_status: "pending",
    notes: "First time voter. Enthusiastic about public library initiative.",
    created_at: "2026-02-01T10:00:00Z",
    last_contacted_by: "Amit Kumar",
    last_contacted_at: "2026-03-16T15:00:00Z",
  },
  {
    id: "voter-101-5",
    client_id: "client-1",
    campaign_id: "camp-1",
    booth_id: "booth-101",
    booth_number: "Booth 101",
    booth_name: "Govt Inter College, Room 1",
    area_id: "area-1",
    area_name: "Hazratganj Main",
    voter_id_card: "UP/48/281/001425",
    name: "Mohd. Tariq Khan",
    mobile: "+91 99350 88991",
    age: 41,
    gender: "Male",
    address: "Shop 14, Halwasiya Market, Hazratganj",
    contact_status: "uncontacted",
    follow_up_status: "none",
    notes: "Scheduled for door-to-door visit this week.",
    created_at: "2026-02-01T10:00:00Z",
  },
  {
    id: "voter-101-6",
    client_id: "client-1",
    campaign_id: "camp-1",
    booth_id: "booth-101",
    booth_number: "Booth 101",
    booth_name: "Govt Inter College, Room 1",
    area_id: "area-1",
    area_name: "Hazratganj Main",
    voter_id_card: "UP/48/281/001426",
    name: "Fatima Khan",
    mobile: "+91 99350 88992",
    age: 38,
    gender: "Female",
    address: "H.No 18/B, Halwasiya Lane, Hazratganj",
    contact_status: "uncontacted",
    follow_up_status: "none",
    notes: "",
    created_at: "2026-02-01T10:00:00Z",
  },
  {
    id: "voter-101-7",
    client_id: "client-1",
    campaign_id: "camp-1",
    booth_id: "booth-101",
    booth_number: "Booth 101",
    booth_name: "Govt Inter College, Room 1",
    area_id: "area-1",
    area_name: "Hazratganj Main",
    voter_id_card: "UP/48/281/001427",
    name: "Dr. Arvind Saxena",
    mobile: "+91 94150 99001",
    age: 62,
    gender: "Male",
    address: "Saxena Clinic, Butler Road, Hazratganj",
    contact_status: "favorable",
    follow_up_status: "none",
    notes: "Senior doctor. Influential in local doctors association.",
    created_at: "2026-02-01T10:00:00Z",
    last_contacted_by: "Amit Kumar",
    last_contacted_at: "2026-03-14T17:00:00Z",
  },
  {
    id: "voter-101-8",
    client_id: "client-1",
    campaign_id: "camp-1",
    booth_id: "booth-101",
    booth_number: "Booth 101",
    booth_name: "Govt Inter College, Room 1",
    area_id: "area-1",
    area_name: "Hazratganj Main",
    voter_id_card: "UP/48/281/001428",
    name: "Shyam Lal Maurya",
    mobile: "+91 98380 22334",
    age: 47,
    gender: "Male",
    address: "Quarter 5, PWD Colony, Hazratganj",
    contact_status: "not_available",
    follow_up_status: "pending",
    notes: "Door was locked during 1st round. Revisit in evening.",
    created_at: "2026-02-01T10:00:00Z",
    last_contacted_by: "Amit Kumar",
    last_contacted_at: "2026-03-17T10:30:00Z",
  },

  // Client 1 - Booth 102 Voters
  {
    id: "voter-102-1",
    client_id: "client-1",
    campaign_id: "camp-1",
    booth_id: "booth-102",
    booth_number: "Booth 102",
    booth_name: "Govt Girls High School, Room 3",
    area_id: "area-1",
    area_name: "Hazratganj Main",
    voter_id_card: "UP/48/281/002011",
    name: "Neelam Tandon",
    mobile: "+91 94500 11221",
    age: 43,
    gender: "Female",
    address: "H.No 24, MG Marg, Hazratganj",
    contact_status: "favorable",
    follow_up_status: "none",
    notes: "Active in resident welfare association.",
    created_at: "2026-02-02T10:00:00Z",
    last_contacted_by: "Sunita Tripathi",
    last_contacted_at: "2026-03-16T16:20:00Z",
  },
  {
    id: "voter-102-2",
    client_id: "client-1",
    campaign_id: "camp-1",
    booth_id: "booth-102",
    booth_number: "Booth 102",
    booth_name: "Govt Girls High School, Room 3",
    area_id: "area-1",
    area_name: "Hazratganj Main",
    voter_id_card: "UP/48/281/002012",
    name: "Gaurav Tandon",
    mobile: "+91 94500 11222",
    age: 46,
    gender: "Male",
    address: "H.No 24, MG Marg, Hazratganj",
    contact_status: "undecided",
    follow_up_status: "pending",
    notes: "Wants candidate to personally visit the market association.",
    created_at: "2026-02-02T10:00:00Z",
    last_contacted_by: "Sunita Tripathi",
    last_contacted_at: "2026-03-16T16:35:00Z",
  },
  {
    id: "voter-102-3",
    client_id: "client-1",
    campaign_id: "camp-1",
    booth_id: "booth-102",
    booth_number: "Booth 102",
    booth_name: "Govt Girls High School, Room 3",
    area_id: "area-1",
    area_name: "Hazratganj Main",
    voter_id_card: "UP/48/281/002013",
    name: "Kavita Rastogi",
    mobile: "+91 97210 55443",
    age: 35,
    gender: "Female",
    address: "Flat 101, Gomti View Enclave, Hazratganj",
    contact_status: "uncontacted",
    follow_up_status: "none",
    notes: "",
    created_at: "2026-02-02T10:00:00Z",
  },
  {
    id: "voter-102-4",
    client_id: "client-1",
    campaign_id: "camp-1",
    booth_id: "booth-102",
    booth_number: "Booth 102",
    booth_name: "Govt Girls High School, Room 3",
    area_id: "area-1",
    area_name: "Hazratganj Main",
    voter_id_card: "UP/48/281/002014",
    name: "Alok Pandey",
    mobile: "+91 98390 12890",
    age: 39,
    gender: "Male",
    address: "H.No 78, Sapru Marg, Hazratganj",
    contact_status: "unfavorable",
    follow_up_status: "none",
    notes: "Committed to rival candidate due to caste affiliation.",
    created_at: "2026-02-02T10:00:00Z",
    last_contacted_by: "Sunita Tripathi",
    last_contacted_at: "2026-03-15T12:00:00Z",
  },

  // Client 1 - Booth 103 Voters (Alambagh)
  {
    id: "voter-103-1",
    client_id: "client-1",
    campaign_id: "camp-1",
    booth_id: "booth-103",
    booth_number: "Booth 103",
    booth_name: "Alambagh Community Center, Hall A",
    area_id: "area-2",
    area_name: "Alambagh Market",
    voter_id_card: "UP/48/281/003101",
    name: "Harjeet Singh",
    mobile: "+91 98390 77112",
    age: 52,
    gender: "Male",
    address: "Shop 5, Guru Nanak Market, Alambagh",
    contact_status: "favorable",
    follow_up_status: "none",
    notes: "President of Gurdwara Committee. Strong community reach.",
    created_at: "2026-02-03T10:00:00Z",
    last_contacted_by: "Vikas Mishra",
    last_contacted_at: "2026-03-16T18:00:00Z",
  },
  {
    id: "voter-103-2",
    client_id: "client-1",
    campaign_id: "camp-1",
    booth_id: "booth-103",
    booth_number: "Booth 103",
    booth_name: "Alambagh Community Center, Hall A",
    area_id: "area-2",
    area_name: "Alambagh Market",
    voter_id_card: "UP/48/281/003102",
    name: "Jaspreet Kaur",
    mobile: "+91 98390 77113",
    age: 48,
    gender: "Female",
    address: "H.No 64, Chander Nagar, Alambagh",
    contact_status: "favorable",
    follow_up_status: "none",
    notes: "Supported our cleanliness drive last month.",
    created_at: "2026-02-03T10:00:00Z",
    last_contacted_by: "Vikas Mishra",
    last_contacted_at: "2026-03-16T18:15:00Z",
  },
  {
    id: "voter-103-3",
    client_id: "client-1",
    campaign_id: "camp-1",
    booth_id: "booth-103",
    booth_number: "Booth 103",
    booth_name: "Alambagh Community Center, Hall A",
    area_id: "area-2",
    area_name: "Alambagh Market",
    voter_id_card: "UP/48/281/003103",
    name: "Pawan Yadav",
    mobile: "+91 94150 66554",
    age: 31,
    gender: "Male",
    address: "H.No 112, Singar Nagar, Alambagh",
    contact_status: "undecided",
    follow_up_status: "pending",
    notes: "Looking for road resurfacing commitment near his street.",
    created_at: "2026-02-03T10:00:00Z",
    last_contacted_by: "Vikas Mishra",
    last_contacted_at: "2026-03-17T11:45:00Z",
  },
  {
    id: "voter-103-4",
    client_id: "client-1",
    campaign_id: "camp-1",
    booth_id: "booth-103",
    booth_number: "Booth 103",
    booth_name: "Alambagh Community Center, Hall A",
    area_id: "area-2",
    area_name: "Alambagh Market",
    voter_id_card: "UP/48/281/003104",
    name: "Sunil Sahu",
    mobile: "+91 97920 33441",
    age: 36,
    gender: "Male",
    address: "H.No 89, Sujanpura, Alambagh",
    contact_status: "uncontacted",
    follow_up_status: "none",
    notes: "",
    created_at: "2026-02-03T10:00:00Z",
  },

  // Client 2 - Booth 201 Voters (Strictly Isolated Tenant)
  {
    id: "voter-201-1",
    client_id: "client-2",
    campaign_id: "camp-2",
    booth_id: "booth-201",
    booth_number: "Booth 21",
    booth_name: "Prathmik Vidyalaya Cantt",
    area_id: "area-4",
    area_name: "Cantonment North",
    voter_id_card: "UP/54/310/009112",
    name: "Dinesh Keshari",
    mobile: "+91 94500 88123",
    age: 44,
    gender: "Male",
    address: "Ward 14, Cantt Bazar, Varanasi",
    contact_status: "favorable",
    follow_up_status: "none",
    notes: "Supports Priya Verma for municipal election.",
    created_at: "2026-02-12T10:00:00Z",
    last_contacted_by: "Ramesh Pandey",
    last_contacted_at: "2026-03-14T10:00:00Z",
  },
  {
    id: "voter-201-2",
    client_id: "client-2",
    campaign_id: "camp-2",
    booth_id: "booth-201",
    booth_number: "Booth 21",
    booth_name: "Prathmik Vidyalaya Cantt",
    area_id: "area-4",
    area_name: "Cantonment North",
    voter_id_card: "UP/54/310/009113",
    name: "Sarita Keshari",
    mobile: "+91 94500 88124",
    age: 40,
    gender: "Female",
    address: "Ward 14, Cantt Bazar, Varanasi",
    contact_status: "contacted",
    follow_up_status: "none",
    notes: "Requested drainage repair before monsoon.",
    created_at: "2026-02-12T10:00:00Z",
    last_contacted_by: "Ramesh Pandey",
    last_contacted_at: "2026-03-14T10:20:00Z",
  },
];

export const INITIAL_TASKS: Task[] = [
  // Client 1 Tasks
  {
    id: "task-1",
    client_id: "client-1",
    campaign_id: "camp-1",
    volunteer_id: "vol-1",
    volunteer_name: "Amit Kumar",
    booth_id: "booth-101",
    booth_name: "Booth 101 (Govt Inter College)",
    area_id: "area-1",
    area_name: "Hazratganj Main",
    title: "Distribute Voter Slip Packets (Voters 1-50)",
    description: "Hand deliver official candidate voter slips and manifesto flyers to Park Road and Jopling Road.",
    priority: "high",
    due_date: "2026-09-05",
    status: "in_progress",
    created_at: "2026-03-10T10:00:00Z",
  },
  {
    id: "task-2",
    client_id: "client-1",
    campaign_id: "camp-1",
    volunteer_id: "vol-1",
    volunteer_name: "Amit Kumar",
    booth_id: "booth-101",
    booth_name: "Booth 101 (Govt Inter College)",
    area_id: "area-1",
    area_name: "Hazratganj Main",
    title: "Verify First-Time Voters List",
    description: "Identify young voters aged 18-24 in Booth 101 and invite them to the Sunday Youth Conclave.",
    priority: "urgent",
    due_date: "2026-09-03",
    status: "pending",
    created_at: "2026-03-12T11:00:00Z",
  },
  {
    id: "task-3",
    client_id: "client-1",
    campaign_id: "camp-1",
    volunteer_id: "vol-2",
    volunteer_name: "Sunita Tripathi",
    booth_id: "booth-102",
    booth_name: "Booth 102 (Govt Girls High School)",
    area_id: "area-1",
    area_name: "Hazratganj Main",
    title: "Women's Self-Help Group Outreach Meeting",
    description: "Coordinate with 3 local SHG leaders near Sapru Marg for evening tea discussion with candidate spouse.",
    priority: "medium",
    due_date: "2026-09-08",
    status: "pending",
    created_at: "2026-03-14T09:30:00Z",
  },
  {
    id: "task-4",
    client_id: "client-1",
    campaign_id: "camp-1",
    volunteer_id: "vol-3",
    volunteer_name: "Vikas Mishra",
    booth_id: "booth-103",
    booth_name: "Booth 103 (Alambagh Community Center)",
    area_id: "area-2",
    area_name: "Alambagh Market",
    title: "Merchant Association Banner Installation",
    description: "Place official banners at approved designated corner shops along Chander Nagar road.",
    priority: "low",
    due_date: "2026-09-10",
    status: "completed",
    created_at: "2026-03-08T14:00:00Z",
  },

  // Client 2 Tasks
  {
    id: "task-201",
    client_id: "client-2",
    campaign_id: "camp-2",
    volunteer_id: "vol-201",
    volunteer_name: "Ramesh Pandey",
    booth_id: "booth-201",
    booth_name: "Booth 21 (Prathmik Vidyalaya Cantt)",
    area_id: "area-4",
    area_name: "Cantonment North",
    title: "Sanitation Survey & Grievance Registration",
    description: "Note down open drain issues in Cantt Bazar lane 3.",
    priority: "high",
    due_date: "2026-09-06",
    status: "in_progress",
    created_at: "2026-03-12T10:00:00Z",
  },
];

export const INITIAL_FIELD_ACTIVITIES: FieldActivity[] = [
  // Client 1 Activities
  {
    id: "act-1",
    client_id: "client-1",
    campaign_id: "camp-1",
    volunteer_id: "vol-1",
    volunteer_name: "Amit Kumar",
    voter_id: "voter-101-1",
    voter_name: "Suresh Chandra Gupta",
    voter_card: "UP/48/281/001421",
    booth_name: "Booth 101",
    activity_type: "door_to_door",
    outcome: "Supporter / Favorable",
    notes: "Family of 4 will cast vote by 9:30 AM. Very supportive.",
    created_at: "2026-03-15T11:20:00Z",
  },
  {
    id: "act-2",
    client_id: "client-1",
    campaign_id: "camp-1",
    volunteer_id: "vol-1",
    volunteer_name: "Amit Kumar",
    voter_id: "voter-101-3",
    voter_name: "Rohit Agarwal",
    voter_card: "UP/48/281/001423",
    booth_name: "Booth 101",
    activity_type: "door_to_door",
    outcome: "Undecided - Follow up required",
    notes: "Spoke for 15 mins. Shared details on urban development fund.",
    created_at: "2026-03-16T14:10:00Z",
  },
  {
    id: "act-3",
    client_id: "client-1",
    campaign_id: "camp-1",
    volunteer_id: "vol-2",
    volunteer_name: "Sunita Tripathi",
    voter_id: "voter-102-1",
    voter_name: "Neelam Tandon",
    voter_card: "UP/48/281/002011",
    booth_name: "Booth 102",
    activity_type: "door_to_door",
    outcome: "Favorable",
    notes: "Discussed street lights and CCTV camera plan.",
    created_at: "2026-03-16T16:20:00Z",
  },
  {
    id: "act-4",
    client_id: "client-1",
    campaign_id: "camp-1",
    volunteer_id: "vol-3",
    volunteer_name: "Vikas Mishra",
    voter_id: "voter-103-1",
    voter_name: "Harjeet Singh",
    voter_card: "UP/48/281/003101",
    booth_name: "Booth 103",
    activity_type: "meeting",
    outcome: "Strong Supporter",
    notes: "Met at shop. Guaranteed booth level mobilization support.",
    created_at: "2026-03-16T18:00:00Z",
  },
];

export const INITIAL_FOLLOW_UPS: FollowUp[] = [
  // Client 1 Follow-ups
  {
    id: "fup-1",
    client_id: "client-1",
    campaign_id: "camp-1",
    voter_id: "voter-101-3",
    voter_name: "Rohit Agarwal",
    voter_card: "UP/48/281/001423",
    voter_mobile: "+91 98390 44551",
    voter_address: "Flat 402, Royal Apartments, Hazratganj",
    booth_name: "Booth 101",
    volunteer_id: "vol-1",
    volunteer_name: "Amit Kumar",
    scheduled_date: "2026-09-02",
    priority: "high",
    status: "pending",
    note: "Provide physical copy of manifesto and clarify parking solution plan.",
    created_at: "2026-03-16T14:15:00Z",
  },
  {
    id: "fup-2",
    client_id: "client-1",
    campaign_id: "camp-1",
    voter_id: "voter-101-4",
    voter_name: "Ananya Dixit",
    voter_card: "UP/48/281/001424",
    voter_mobile: "+91 97920 66772",
    voter_address: "H.No 45, Jopling Road, Hazratganj",
    booth_name: "Booth 101",
    volunteer_id: "vol-1",
    volunteer_name: "Amit Kumar",
    scheduled_date: "2026-09-03",
    priority: "medium",
    status: "pending",
    note: "Deliver Youth Conclave badge and pass for candidate interaction.",
    created_at: "2026-03-16T15:05:00Z",
  },
  {
    id: "fup-3",
    client_id: "client-1",
    campaign_id: "camp-1",
    voter_id: "voter-101-8",
    voter_name: "Shyam Lal Maurya",
    voter_card: "UP/48/281/001428",
    voter_mobile: "+91 98380 22334",
    voter_address: "Quarter 5, PWD Colony, Hazratganj",
    booth_name: "Booth 101",
    volunteer_id: "vol-1",
    volunteer_name: "Amit Kumar",
    scheduled_date: "2026-09-02",
    priority: "medium",
    status: "pending",
    note: "Second attempt door-to-door visit (evening time after 6:30 PM).",
    created_at: "2026-03-17T10:35:00Z",
  },
  {
    id: "fup-4",
    client_id: "client-1",
    campaign_id: "camp-1",
    voter_id: "voter-102-2",
    voter_name: "Gaurav Tandon",
    voter_card: "UP/48/281/002012",
    voter_mobile: "+91 94500 11222",
    voter_address: "H.No 24, MG Marg, Hazratganj",
    booth_name: "Booth 102",
    volunteer_id: "vol-2",
    volunteer_name: "Sunita Tripathi",
    scheduled_date: "2026-09-04",
    priority: "high",
    status: "pending",
    note: "Arrange brief 5-minute phone call with candidate Rajesh Sharma.",
    created_at: "2026-03-16T16:40:00Z",
  },
  {
    id: "fup-5",
    client_id: "client-1",
    campaign_id: "camp-1",
    voter_id: "voter-103-3",
    voter_name: "Pawan Yadav",
    voter_card: "UP/48/281/003103",
    voter_mobile: "+91 94150 66554",
    voter_address: "H.No 112, Singar Nagar, Alambagh",
    booth_name: "Booth 103",
    volunteer_id: "vol-3",
    volunteer_name: "Vikas Mishra",
    scheduled_date: "2026-09-05",
    priority: "medium",
    status: "pending",
    note: "Follow up with written proposal on municipal road work sanction.",
    created_at: "2026-03-17T11:50:00Z",
  },
];

export const INITIAL_SUBSCRIPTIONS: Subscription[] = [
  {
    id: "sub-1",
    client_id: "client-1",
    client_name: "Sharma Campaign HQ",
    plan_name: "assembly_pro",
    max_voters: 150000,
    max_volunteers: 100,
    status: "active",
    valid_until: "2026-12-31T23:59:59Z",
    created_at: "2026-01-10T10:00:00Z",
  },
  {
    id: "sub-2",
    client_id: "client-2",
    client_name: "Verma Vikas Samiti",
    plan_name: "ward_starter",
    max_voters: 25000,
    max_volunteers: 20,
    status: "active",
    valid_until: "2026-11-30T23:59:59Z",
    created_at: "2026-02-01T11:30:00Z",
  },
  {
    id: "sub-3",
    client_id: "client-3",
    client_name: "Deshmukh Janshakti Office",
    plan_name: "parliament_enterprise",
    max_voters: 500000,
    max_volunteers: 500,
    status: "active",
    valid_until: "2027-01-31T23:59:59Z",
    created_at: "2026-02-15T09:15:00Z",
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: "log-1",
    client_id: "client-1",
    client_name: "Sharma Campaign HQ",
    actor_id: "user-super-admin",
    actor_name: "Vikramaditya Rao (Super Admin)",
    action: "TENANT_PROVISIONED",
    target_type: "Client",
    target_id: "client-1",
    details: { plan: "assembly_pro", candidate: "Rajesh Sharma" },
    created_at: "2026-01-10T10:00:00Z",
  },
  {
    id: "log-2",
    client_id: "client-1",
    client_name: "Sharma Campaign HQ",
    actor_id: "user-client-1",
    actor_name: "Rajesh Sharma",
    action: "VOTER_LIST_IMPORTED",
    target_type: "Voters",
    target_id: "batch-01",
    details: { total_imported: 48, booths_covered: 4 },
    created_at: "2026-02-01T10:15:00Z",
  },
  {
    id: "log-3",
    client_id: "client-1",
    client_name: "Sharma Campaign HQ",
    actor_id: "user-client-1",
    actor_name: "Rajesh Sharma",
    action: "VOLUNTEER_ASSIGNED",
    target_type: "Volunteer",
    target_id: "vol-1",
    details: { volunteer: "Amit Kumar", booth: "Booth 101" },
    created_at: "2026-03-01T10:05:00Z",
  },
  {
    id: "log-4",
    client_id: "client-1",
    client_name: "Sharma Campaign HQ",
    actor_id: "user-volunteer-1",
    actor_name: "Amit Kumar (Volunteer)",
    action: "FIELD_ACTIVITY_RECORDED",
    target_type: "FieldActivity",
    target_id: "act-1",
    details: { voter: "Suresh Chandra Gupta", outcome: "Favorable" },
    created_at: "2026-03-15T11:20:00Z",
  },
];
